### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by Edzilla2000** [mtlynch/resticpy#136]
Hi, 
First of all, let me thank you for this, it's really helpful.
I'm using it to automatically verify backups and it's going great.
Unfortunately the latest release (1.0.2) does not include the "read_data_subset", although the code in the repository does. Would it be possible to release a new version?
Thanks!

**Comment by mtlynch** [comment]
@Edzilla2000 - Thanks for the reminder! I've just published a new release:

https://github.com/mtlynch/resticpy/releases/tag/1.0.3
