### ISSUE TITLE
restic.forget() does not support specifying host/tags

### ISSUE THREAD

**Issue by mschulze46** [mtlynch/resticpy#139]
Thanks very much for your great wrapper!

What I am missing is specifying host and tags in the forget method.

Via CLI the following is possible:

- Remove snapshots filtered by tag(s) with policy:
`restic forget --tag <tag1>[,<tag2>,<tag3>] --keep-last 3`

- Remove snapshots filtered by host with policy:
`restic forget --host <hostname> --keep-last 3`

Cheers
Michael

**Comment by mtlynch** [comment]
Thanks for the kind words!

Due to time constraints, I'm no longer able to take on feature requests:

https://github.com/mtlynch/resticpy#resticpys-scope-and-future

But that would be a fairly narrowly-scoped change, so if you wanted to contribute the change, I'd accept the PR.

**Comment by mschulze46** [comment]
> Thanks for the kind words!
> 
> Due to time constraints, I'm no longer able to take on feature requests:
> 
> https://github.com/mtlynch/resticpy#resticpys-scope-and-future
> 
> But that would be a fairly narrowly-scoped change, so if you wanted to contribute the change, I'd accept the PR.

Thanks for your feedback. I will create a PR.

**Comment by mtlynch** [comment]
@mschulze46 - Thanks for this fix! The update is now released in v1.0.4 on pip.
