### ISSUE TITLE
Feature request - Restic restore exclude parameter

### ISSUE THREAD

**Issue by S0obi** [mtlynch/resticpy#159]
Hello everyone,

We have currently a need to support the `--exclude` parameter while using the restic.restore method. Unfortunately, only `--include` is supported currently, then we have no other choice than relying on executing the restic command without using this library.

Thanks in advance.

**Comment by mtlynch** [comment]
Thanks for reporting this.

Just for clarification, I'm not part of the restic team. I just created this library for my own use and open-sourced the code. See the scope here:

https://github.com/mtlynch/resticpy?tab=readme-ov-file#resticpys-scope-and-future

**Comment by S0obi** [comment]
Hello there ! Thanks for your prompt reply. It seems like it's not a complex change, I will create a PR and let you decide if you want to add it to the code base.

Thanks for sharing this project.
Thibault
