### ISSUE TITLE
Feature request: filter snapshots on path

### ISSUE THREAD

**Issue by jwellner** [mtlynch/resticpy#162]
Thanks for creating and maintaining this project!

I started to use it and it works great! I only need to filter snapshots on specific paths. 

Right now I filter the results myself but it would be nice if we could use:

`restic.snapshots(path='/backup/path/site')` (and maybe also implement the host filter?)

**Comment by mtlynch** [comment]
Thanks for reporting this!

I [don't implement feature requests](https://github.com/mtlynch/resticpy?tab=readme-ov-file#resticpys-scope-and-future), but I'm happy to accept the PR for this if you or someone else would like to implement it.
