### ISSUE TITLE
Feature request: skip-if-unchanged

### ISSUE THREAD

**Issue by shaankhosla** [mtlynch/resticpy#187]
Would you be open to a PR that adds support for skipping backup if no files have changed?

**Comment by mtlynch** [comment]
@shaankhosla - Sure. I didn't know that flag existed. Sounds useful!

**Comment by shaankhosla** [comment]
This is the flag: https://restic.readthedocs.io/en/stable/040_backup.html#skip-creating-snapshots-if-unchanged
